name: agendamento_app
description: "App de agendamento - Flutter (iOS, Android, Web) + Backend Go"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  table_calendar: ^3.2.0
  http: ^1.4.0
  intl: ^0.20.2
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
